### ISSUE TITLE
Wrong number of arguments (0 for 1)

### ISSUE THREAD

**Issue by Flox06** [apotonick/apotomo#145]
Hello :)

I've a very boring error using rails 4.0.3 and ruby 2.1.
The problem is that args seem to be not passed to the widget properly.
I tried on an empty projet ( excluding other gem conflicts), but no changes.

Here's the error : 

![errrtt](https://f.cloud.github.com/assets/1890520/2415998/e6faa87a-aafc-11e3-86b7-3d763d75f1f6.png)

Here's the Widget : 

``` ruby
class DiscussWidget < Apotomo::Widget

  responds_to_event :contact_req

  def display(args)
    @message = args[:contact_req]
    render
  end
end
```

And the controller : 

``` ruby
class Admin::MessagesController < ApplicationController

  before_action :set_contact_request, only: [:show, :update, :toggle, :destroy]

  has_widgets do |root|
    root << widget(:discuss, :contact_req => @message)
  end
...
```

I followed all the steps properly, this problem drives me crazy !!

Any chance for help ? =)
Many thanks for your work ! :+1:

**Comment by vishakhasawant** [comment]
We have similar kind of requirement in our new project. I am trying to follow the example from README. Facing few issues with it. I able to resolve issue of not calling 'post' event by adding 'responds_to_event :post, :with => :post'. 
Now I am facing this issue for 
```ruby
   update :state => :display
```

I was not able to pass parameter to display method. I able to resolve this issue as below. I am not sure if that is the right way.
```ruby
class CommentsWidget < Apotomo::Widget
  responds_to_event :post, :with => :post
  
  def display(*args) 
    binding.pry  
    @comments = args[0][:post].comments if !args[0].nil?
    @comments = Post.find(params[:id]).comments if @comments.nil? and !params[:id].nil?
    @comments = Post.find(params[:comment][:post_id]).comments if @comments.nil? and !params[:comment][:post_id].nil?
    render
  end

  def write
    render
  end
  
  def post(event)    
    @comment = Comment.new :post_id => event[:comment][:post_id]
    @comment.update_attributes(desc: event[:comment][:desc]) # a bit like params[].
    
    update :state => :display, :post => @comment.post
    
  end

end
```

Would you please validate above code? Many Thanks for such a great gem.

**Comment by vishakhasawant** [comment]
Awaiting for your response on above issue..........

**Comment by apotonick** [comment]
Is the problem that

```ruby
update :state => :display, :post => @comment.post
```

doesn't pass the `post: ..` to `#display`?

**Comment by vishakhasawant** [comment]
Thanks for the response. Yes. Right, I am talking about the same. Is there any better workaround available?

**Comment by apotonick** [comment]
You might have to use `:locals`, as in 

```ruby
update :state => :display, locals: { :post => @comment.post }
```

Does that work? Sorry again, but Apotomo currently has the lowest priority on my evergrowing TODO list... But it will be back with more love one day!

**Comment by vishakhasawant** [comment]
Thanks for the reply. No. It doesn't.
