### ISSUE TITLE
uninitialized constant Cell::Rails (NameError) - Cell 4.0.0

### ISSUE THREAD

**Issue by nedden** [apotonick/apotomo#157]
Hi! 

I got this error after bundle update.

```
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/apotomo-1.3.1/lib/apotomo/widget.rb:38:in `<module:Apotomo>': uninitialized constant Cell::Rails (NameError)
        from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/apotomo-1.3.1/lib/apotomo/widget.rb:16:in `<top (required)>'
        from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/apotomo-1.3.1/lib/apotomo.rb:23:in `<top (required)>'
....

```

This link to upgrade howto:

https://github.com/apotonick/cells/wiki/From-Cells-3-to-Cells-4---Upgrading-Guide
>The old dialect Cell::Base and Cell::Rails got superceded by Cell::ViewModel. So, every cell should start like

```ruby
class SongCell < Cell::ViewModel
  def show
    render
  end
```

**Comment by apotonick** [comment]
Hi! Sorry to disappoint you but Apotomo does not work with Cells 4. I'm gonna supercede Apotomo with [cells-widget](http://github.com/apotonick/cells-widget).

I want to start working on that as it's actually not that hard. Are you ok with using Cells 3 + Apotomo?

**Comment by nedden** [comment]
Yes, Im' fine with Cells 3. But you need to change dependency < 4.0.0, otherwise it will update Cells to 4.0.0

```ruby
s.add_dependency "cells",   ">= 3.6.7"
```

**Comment by nedden** [comment]
Hi! Sorry, maybe I didn't explain properly or it is lack of my english. I did update my gems by **bundle update**
All gems were updated  including **Cell** to the version **4.0.0**, because the version of  Cell is not restricted by "<4.0.0"

It means my application is broken now without reason :)

**Comment by apotonick** [comment]
I understood your english because it is perfect. :grin:
